#!/bin/sh
set -eu

source_file="$(dirname "$0")/../antforest/AntForestManager.m"
entry_file="$(dirname "$0")/../PortEntry.m"
header_file="$(dirname "$0")/../antforest/AntForestManager.h"
makefile="$(dirname "$0")/../Makefile"

echo "[1/4] Checking AntForestManager.h Manor declarations..."
grep -Fq 'enableAutoManor' "$header_file"
grep -Fq 'manorBridge' "$header_file"
grep -Fq 'manorH5Url' "$header_file"
grep -Fq 'handleManorResponse:' "$header_file"
grep -Fq 'queryManorTaskList' "$header_file"
grep -Fq 'handleManorTaskList:' "$header_file"
grep -Fq 'finishManorTask:' "$header_file"
grep -Fq 'receiveManorTaskAward:' "$header_file"
grep -Fq 'executeManorScriptOnWebView:' "$header_file"
grep -Fq 'signManorDaily' "$header_file"
grep -Fq 'answerManorClassroomQuestion' "$header_file"
grep -Fq 'runManorTasks' "$header_file"
grep -Fq 'feedManorChicken' "$header_file"
grep -Fq 'enterManorFarm' "$header_file"
grep -Fq 'collectManorChickenManure' "$header_file"

echo "[2/4] Checking AntForestManager.m Manor implementation..."
grep -Fq 'executeManorScriptOnWebView:' "$source_file"
grep -Fq 'signManorDaily' "$source_file"
grep -Fq 'executeClassroomAnswerScript' "$source_file"
grep -Fq 'answerManorClassroomQuestion' "$source_file"
grep -Fq 'executeManorTaskProcessScript' "$source_file"
grep -Fq 'runManorTasks' "$source_file"
grep -Fq 'queryManorTaskList' "$source_file"
grep -Fq 'handleManorTaskList:' "$source_file"
grep -Fq 'finishManorTask:' "$source_file"
grep -Fq 'receiveManorTaskAward:' "$source_file"
grep -Fq 'feedManorChicken' "$source_file"
grep -Fq 'enterManorFarm' "$source_file"
grep -Fq 'collectManorChickenManure' "$source_file"
grep -Fq 'handleManorResponse:' "$source_file"
grep -Fq 'subFarmVO' "$source_file"
grep -Fq 'farmTaskList' "$source_file"
grep -Fq 'signList' "$source_file"
grep -Fq 'ANTFARM_FOOD_TASK' "$source_file"
grep -Fq 'QA_DB' "$source_file"
grep -Fq 'com.alipay.antfarm.feedAnimal' "$source_file"
grep -Fq 'com.alipay.antfarm.enterFarm' "$source_file"
grep -Fq 'com.alipay.antfarm.sign' "$source_file"
grep -Fq 'openManorTaskPanelOnWebView' "$source_file"
grep -Fq 'closeManorTaskPanelOnWebView' "$source_file"
grep -Fq 'isManorChickenEating' "$source_file"
grep -Fq 'com.alipay.antfarm.collectManurePot' "$source_file"
grep -Fq 'com.alipay.antfarm.syncAnimalStatus' "$source_file"
grep -Fq 'com.alipay.antfarm.listFarmTask' "$source_file"
grep -Fq 'com.alipay.antfarm.doFarmTask' "$source_file"
grep -Fq 'com.alipay.antfarm.receiveFarmTaskAward' "$source_file"
grep -Fq 'TRIGGER' "$source_file"
grep -Fq 'taskDelayIndex' "$source_file"
grep -Fq 'lastKnownUserId' "$source_file"

echo "[3/4] Checking PortEntry.m UI & Hook integration..."
grep -Fq 'toggleAutoManor:' "$entry_file"
grep -Fq '蚂蚁庄园' "$entry_file"
grep -Fq '蚂蚁庄园=' "$entry_file"
grep -Fq 'enableAutoManor' "$entry_file"
grep -Fq 'manager.manorBridge = self;' "$entry_file"
grep -Fq 'checkAndRunManorAutomations' "$entry_file"
grep -Fq 'handleManorResponse:' "$entry_file"
grep -Fq 'ManorProbe-RPC-REQ' "$entry_file"

echo "[4/4] Checking dylib build outputs..."
test -f "$(dirname "$0")/../build/AntForestPort-Ocean.dylib"
test -f "$(dirname "$0")/../build/AntForestPort-Ocean-iOS14.dylib"

echo "✅ All Manor automation checks passed successfully!"
