name: Build AntForest

on:
  workflow_dispatch:
  push:
    branches: [ "dev-1" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main
      - name: Build dylib
        run: |
          rm -rf build
          make all

      - name: Run tests
        run: |
          make test

      - name: Install dpkg
        run: |
          brew install dpkg

      - name: Build packages
        run: |
          mkdir -p Packages build/rootless-tmp
          rm -rf Packages/*.deb build/rootless-tmp/*
          VER=$(grep '^Version:' antforest/Package/DEBIAN/control | awk '{print $2}')
          echo "Package version: ${VER}"

          # Rootful
          #cp -r antforest/Package/* build/rootful-tmp/
          #cp build/AntForestPort-Ocean.dylib build/rootful-tmp/Library/MobileSubstrate/DynamicLibraries/antforest.dylib
          #dpkg-deb -b build/rootful-tmp "Packages/com.vknote.antforest_${VER}_iphoneos-arm.deb"

          # Rootless
          cp -r antforest/Package/* build/rootless-tmp/
          sed -i '' 's/^Architecture: iphoneos-arm/Architecture: iphoneos-arm64/' build/rootless-tmp/DEBIAN/control
          mkdir -p build/rootless-tmp/var/jb/Library/MobileSubstrate/DynamicLibraries
          cp build/AntForestPort-Ocean.dylib build/rootless-tmp/var/jb/Library/MobileSubstrate/DynamicLibraries/antforest.dylib
          dpkg-deb -b build/rootless-tmp "Packages/com.vknote.antforest_${VER}_iphoneos-arm64.deb"

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: AntForest‑Packages
          path: |
            ${{ github.workspace }}/Packages/*.deb
